# Deploy n8n on Render using a PostgreSQL database

services:
  - type: web
    name: n8n-service
    runtime: image
    plan: free

    image:
      # Pin n8n to the old v1 version
      url: docker.io/n8nio/n8n:1.123.81

    envVars:
      # Used by n8n to encrypt credentials
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Automatically enforce secure permissions
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      # n8n uses PostgreSQL
      - key: DB_TYPE
        value: postgresdb

      # PostgreSQL database name
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database

      # PostgreSQL host
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host

      # PostgreSQL password
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

      # PostgreSQL username
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user

      # PostgreSQL port
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port

databases:
  - name: n8n-db
    plan: free
