services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: n8nio/n8n
    plan: free
    region: singapore

    envVars:
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        value: ep-bitter-lake-b54kdt42-pooler.c-7.us-east-2.aws.neon.tech

      - key: DB_POSTGRESDB_PORT
        value: "5432"

      - key: DB_POSTGRESDB_DATABASE
        value: neondb

      - key: DB_POSTGRESDB_USER
        value: neondb_owner

      - key: DB_POSTGRESDB_PASSWORD
        sync: false

      - key: DB_POSTGRESDB_SCHEMA
        value: public

      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"

      - key: DB_PING_TIMEOUT_MS
        value: "10000"

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"

      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"

      - key: EXECUTIONS_DATA_PRUNE
        value: "true"

      - key: EXECUTIONS_DATA_MAX_AGE
        value: "72"

      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: "none"

      - key: N8N_METRICS
        value: "false"

    healthCheckPath: /healthz
